### ISSUE TITLE
Hide objects from the navigation when facetednav is installed

### ISSUE THREAD

**Issue by pcdummy** [collective/collective.contact.facetednav#2]
Is that something we want with c.c.facetednav?

    <?xml version="1.0"?>
    <object name="portal_properties" meta_type="Plone Properties Tool">

     <object name="navtree_properties" meta_type="Plone Property Sheet">
        <property name="metaTypesNotToList" type="lines"
                  purge="False">
          <element value="held_position"/>
          <element value="organization"/>
          <element value="person"/>
          <element value="position"/>
        </property>
      </object>
    </object>

**Comment by pcdummy** [comment]
@frisi  fyi

**Comment by frisi** [comment]
as this has something to do with the content types rather than facetednav integration it should go into `collective.contact.core`.
apart from that i definitely think it makes sense to hide objects of these types in the navigation.

**Comment by vincentfretin** [comment]
Yes, I guess you can do a PR to add this to the profile in collective.contact.core

**Comment by vincentfretin** [comment]
fixed in collective/collective.contact.core#22
